discover:
  require-data-encryption: false
  server-instance-id: ${SERVER_INSTANCE_ID}
  tenant-id: ${TENANT_ID}

server:
  port: 8069
spring:
  jmx:
    enabled: true
    unique-names: true
  application:
    name: DDS
  config:
    import:
      - classpath:/exclude.yml
      - classpath:/datasource.yml
      - classpath:/kafka.yml
      - classpath:/logging.yml
encryption:
  key: ${TEMP_ENCRYPTION_KEY}
management:
  jmx:
    metrics:
      export:
        enabled: true
  server:
    address: 0.0.0.0
  endpoints:
    jmx:
      exposure:
        include: "*"
      domain: dds
    web:
      exposure:
        include: "health,info,metrics"
debezium:
  offset-storage-dir: /tmp/debezium/offsets
  offset-storage-file-name: debezium-offsets.dat
  history-dir: /tmp/debezium/history
  history-file-name: debezium-history.dat
